# Generated by Django 5.2.14 on 2026-05-08 08:42

import django.db.models.deletion
import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registry_id", models.CharField(max_length=50, unique=True)),
                (
                    "plaque_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("elevation", models.IntegerField(blank=True, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("depth_positive", models.FloatField(blank=True, null=True)),
                ("depth_negative", models.FloatField(blank=True, null=True)),
                (
                    "municipality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("valley", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "geology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("limestone", "Limestone"),
                            ("dolomite", "Dolomite"),
                            ("gypsum", "Gypsum"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("last_survey_date", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CaveMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="caves/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("survey_pdf", "Survey PDF"),
                            ("survey_image", "Survey Image"),
                        ],
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="caves.cave",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
